### ISSUE TITLE
Happy hare throws error with DK

### ISSUE THREAD

**Issue by reapola** [DangerKlippers/danger-klipper#137]
I think there is an issue with Happy Hare (https://github.com/moggieuk/Happy-Hare) and Danger Klipper - klipper won't start as it looks like its not assigning the endstop to the stepper_mmu_gear.  In the  HH software you define pre and post extruder sensors and within it has code to assign them where they are used but I think that's failing somewhere in the code difference between mainline and DK.

I've taken a backup of my DK klipper directory so I can switch back if needed to help fault find.

```
MMU Hardware Initialization -------------------------------
Config error
Traceback (most recent call last):
  File "/home/reapola/klipper/klippy/klippy.py", line 265, in _connect
    self._read_config()
  File "/home/reapola/klipper/klippy/klippy.py", line 200, in _read_config
    self.load_object(config, section_config.get_name(), None)
  File "/home/reapola/klipper/klippy/klippy.py", line 184, in load_object
    self.objects[section] = init_func(config.getsection(section))
  File "/home/reapola/klipper/klippy/extras/mmu.py", line 6056, in load_config
    return Mmu(config)
  File "/home/reapola/klipper/klippy/extras/mmu.py", line 632, in __init__
    self._setup_mmu_hardware(config)
  File "/home/reapola/klipper/klippy/extras/mmu.py", line 645, in _setup_mmu_hardware
    self.mmu_toolhead = MmuToolHead(config, self.homing_extruder)
  File "/home/reapola/klipper/klippy/extras/mmu_toolhead.py", line 106, in __init__
    self.kin = MmuKinematics(self, config)
  File "/home/reapola/klipper/klippy/extras/mmu_toolhead.py", line 417, in __init__
    self.rails = [MmuLookupMultiRail(config.getsection('stepper_mmu_' + s), need_position_minmax=mm, default_position_endstop=0.) for a, s, mm in self.axes]
  File "/home/reapola/klipper/klippy/extras/mmu_toolhead.py", line 417, in <listcomp>
    self.rails = [MmuLookupMultiRail(config.getsection('stepper_mmu_' + s), need_position_minmax=mm, default_position_endstop=0.) for a, s, mm in self.axes]
  File "/home/reapola/klipper/klippy/extras/mmu_toolhead.py", line 627, in MmuLookupMultiRail
    rail = MmuPrinterRail(config, need_position_minmax=need_position_minmax, default_position_endstop=default_position_endstop, units_in_radians=units_in_radians)
  File "/home/reapola/klipper/klippy/extras/mmu_toolhead.py", line 555, in __init__
    super(MmuPrinterRail, self).__init__(config, **kwargs)
  File "/home/reapola/klipper/klippy/stepper.py", line 417, in __init__
    endstop_pin = config.get("endstop_pin")
  File "/home/reapola/klipper/klippy/configfile.py", line 85, in get
    return self._get_wrapper(
  File "/home/reapola/klipper/klippy/configfile.py", line 47, in _get_wrapper
    raise error(
configparser.Error: Option 'endstop_pin' in section 'stepper_mmu_gear' must be specified
```

**Comment by rogerlz** [comment]
this should be fixed now!
