### ISSUE TITLE
Bug/Regression: flash-sdcard.sh broken

### ISSUE THREAD

**Issue by Pieterv24** [DangerKlippers/danger-klipper#361]
Commit 542c30e adding noncritical MCU funcionality, causes issues when serialhdl.py is used from the flash-sdcard.sh script.

The following error is thrown.
```
Flashing /home/pi/klipper/out/klipper.bin to /dev/serial/by-id/usb-Klipper_stm32f446xx_430018000450314D35323820-if00
Checking FatFS CFFI Build...
Building FatFS shared library...Done

SD Card Flash Error: 'NoneType' object has no attribute 'get_printer'
Traceback (most recent call last):
  File "/home/pi/klipper/scripts/spi_flash/spi_flash.py", line 1863, in main
    spiflash.run()
  File "/home/pi/klipper/scripts/spi_flash/spi_flash.py", line 1785, in run
    self.run_reactor_task(self.run_reset_upload)
  File "/home/pi/klipper/scripts/spi_flash/spi_flash.py", line 1766, in run_reactor_task
    self.mcu_conn = MCUConnection(
                    ^^^^^^^^^^^^^^
  File "/home/pi/klipper/scripts/spi_flash/spi_flash.py", line 1352, in __init__
    self._serial = serialhdl.SerialReader(self.reactor)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/klipper/klippy/serialhdl.py", line 40, in __init__
    self.danger_options = self.mcu.get_printer().lookup_object(
                          ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_printer'
```

This seems to be caused by the mcu parameter in the constructor being None in this scenario.
Which causes issues in the following snippet of code, due to mcu being none.
```
self.danger_options = self.mcu.get_printer().lookup_object(
    "danger_options"
)
 ```
 
 I also don't seem to be able to find a practical use for the previous line.
 As far as I can see, it does not seem to be referenced anywhere.
 
 At the very least this line should contain a None check.
 Another option would be to remove the line altogether (assuming it does indeed not serve any purpose).

**Comment by rogerlz** [comment]
thanks for the report and the fix!
